### ISSUE TITLE
cron.validate(date) yields invalid result if weekday is specified

### ISSUE THREAD

**Issue by PhilippvK** [Sonic0/cron-converter#19] opened 2024-05-13 08:46 UTC
It seems like the weekday checks in `cron.validate(date)` are off by one day.

To reproduce the issue the following script can be used:

```python
from datetime import date, timedelta
from cron_converter import Cron

today = date.today()
yesterday = today - timedelta(days=1)

dts = [today, yesterday]
for dt in dts:
    cron_strs = ["* * * * 0", "* * * * 1", "* * * * 6", "* * * * 7"]
    for cron_str in cron_strs:
        print("===")
        print("dt", dt)
        print("cron_str", cron_str)
        cron = Cron(cron_str, {"output_weekday_names": True})
        print("cron", cron)
        valid = cron.validate(dt)
        print("valid", valid)
print("===")
```

**Output:**

```
===
dt 2024-05-13
cron_str * * * * 0
cron * * * * SUN
valid True
===
dt 2024-05-13
cron_str * * * * 1
cron * * * * MON
valid False
===
dt 2024-05-13
cron_str * * * * 6
cron * * * * SAT
valid False
===
dt 2024-05-13
cron_str * * * * 7
cron * * * * SUN
valid True
===
dt 2024-05-12
cron_str * * * * 0
cron * * * * SUN
valid False
===
dt 2024-05-12
cron_str * * * * 1
cron * * * * MON
valid False
===
dt 2024-05-12
cron_str * * * * 6
cron * * * * SAT
valid True
===
dt 2024-05-12
cron_str * * * * 7
cron * * * * SUN
valid False
===
```

**Expected Output:**

```
===
dt 2024-05-13
cron_str * * * * 0
cron * * * * SUN
valid FALSE
===
dt 2024-05-13
cron_str * * * * 1
cron * * * * MON
valid TRUE
===
dt 2024-05-13
cron_str * * * * 6
cron * * * * SAT
valid False
===
dt 2024-05-13
cron_str * * * * 7
cron * * * * SUN
valid FALSE
===
dt 2024-05-12
cron_str * * * * 0
cron * * * * SUN
valid TRUE
===
dt 2024-05-12
cron_str * * * * 1
cron * * * * MON
valid False
===
dt 2024-05-12
cron_str * * * * 6
cron * * * * SAT
valid FALSE
===
dt 2024-05-12
cron_str * * * * 7
cron * * * * SUN
valid TRUE
===
```

**Comment by Sonic0** [comment] 2024-05-13 22:24
Hi @PhilippvK, I apologize for the issue you encountered. Thank you for providing the code to reproduce the problem. I will work to fix it as soon as possible.

**Comment by sre-guru** [comment] 2024-05-23 10:44
Hello @Sonic0 , great work with the repo!!
yea just encountered the same. The issue can be fixed by updating units.py --> units[4].alt to start on Monday.
This is because python datetime considers Monday as day 0, while international crontab considers Sunday as day 0.

**Comment by Sonic0** [comment] 2024-05-23 17:08
Hey @sre-guru, thank you very much. I think the problem is with the validate() feature itself. I created a branch with the fix, but I need more time to conduct additional tests.

**Closed** 2024-05-25 17:49 UTC
